// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eckfwidttrznlmpmqtlg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVja2Z3aWR0dHJ6bmxtcG1xdGxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3ODg4NDIsImV4cCI6MjA2NzM2NDg0Mn0.xg7I8IelDM6UpjEGFuI7gd2CuUwifm8cZ1weYtE7pU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});